### ISSUE TITLE
[BUG]: missing 'input_cost_per_token'

### ISSUE THREAD

**Issue by frazakram** [raga-ai-hub/ragaai-catalyst#135]
# Bug Report

**Describe the Bug**
i am encountering a KeyError related to the missing 'input_cost_per_token' key in the model_cost dictionary. in process_llm_result method in llm_tracer.py

**To Reproduce**
Steps or code snippets to reproduce the behavior, like:

```
1. Install AgentNeo using `pip install agentneo`
2. Run the following code:
```py
@tracer.trace_llm(name="llm_call")
def llm_call(
    prompt, max_tokens=512, model=os.getenv("AZURE_OPENAI_MODEL_NAME")
):
    client = AzureOpenAI(
        api_key=os.getenv("AZURE_OPENAI_API_KEY"),
        api_version=os.getenv("AZURE_OPENAI_API_VERSION"),
        azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
    )
    deployment_name = os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME")


    response = client.chat.completions.create(
        model=deployment_name, # This should match your Azure OpenAI deployment name
        messages=[{"role": "user", "content": prompt}],
        max_tokens=max_tokens,
        temperature=0.7,
    )

    return response.choices[0].message.content.strip()

```
3. Launch the dashboard using `launch_dashboard(port=3000)`
4. Observe the error or unexpected behavior.
```
Error in llm 'llm_call': 'input_cost_per_token'
Error in agent 'schedule_assistant': 'input_cost_per_token'
Traceback (most recent call last):
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/take2.py", line 144, in <module>
    schedule_assistant()
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/agentneo/tracing/agent_tracer.py", line 76, in sync_wrapper
    return self._trace_agent_call_sync(
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/agentneo/tracing/agent_tracer.py", line 157, in _trace_agent_call_sync
    result = func(*args, **kwargs)
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/take2.py", line 118, in schedule_assistant
    extracted_activities = llm_call(activities_prompt)
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/agentneo/tracing/llm_tracer.py", line 243, in sync_wrapper
    return func_or_class(*args, **kwargs)
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/take2.py", line 53, in llm_call
    response = client.chat.completions.create(
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/neo/lib/python3.10/site-packages/wrapt/wrappers.py", line 600, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/agentneo/tracing/llm_tracer.py", line 56, in wrapper
    return self.trace_llm_call(wrapped, *args, **kwargs)
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/agentneo/tracing/llm_tracer.py", line 91, in trace_llm_call
    llm_call = self.process_llm_result(
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/agentneo/tracing/llm_tracer.py", line 137, in process_llm_result
    "input": token_usage["input"] * model_cost["input_cost_per_token"],
KeyError: 'input_cost_per_token'

**Expected Behavior**
not give the above error

**Actual Behavior**
Error in llm 'llm_call': 'input_cost_per_token'
Error in agent 'schedule_assistant': 'input_cost_per_token'
Traceback (most recent call last):
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/take2.py", line 144, in <module>
    schedule_assistant()
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/agentneo/tracing/agent_tracer.py", line 76, in sync_wrapper
    return self._trace_agent_call_sync(
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/agentneo/tracing/agent_tracer.py", line 157, in _trace_agent_call_sync
    result = func(*args, **kwargs)
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/take2.py", line 118, in schedule_assistant
    extracted_activities = llm_call(activities_prompt)
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/agentneo/tracing/llm_tracer.py", line 243, in sync_wrapper
    return func_or_class(*args, **kwargs)
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/take2.py", line 53, in llm_call
    response = client.chat.completions.create(
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/neo/lib/python3.10/site-packages/wrapt/wrappers.py", line 600, in __call__
    return self._self_wrapper(self.__wrapped__, instance,
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/agentneo/tracing/llm_tracer.py", line 56, in wrapper
    return self.trace_llm_call(wrapped, *args, **kwargs)
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/agentneo/tracing/llm_tracer.py", line 91, in trace_llm_call
    llm_call = self.process_llm_result(
  File "/Users/ejaz/Desktop/vscode3/AgentNeo/agentneo/tracing/llm_tracer.py", line 137, in process_llm_result
    "input": token_usage["input"] * model_cost["input_cost_per_token"],
KeyError: 'input_cost_per_token'

**Logs and Screenshots**
<img width="1439" alt="Screenshot 2024-12-27 at 11 52 15 AM" src="https://github.com/user-attachments/assets/ff058154-ab7a-498d-9206-42d723d618f5" />


**Environment Details**
- **Operating System**: [e.g., Windows 10, Ubuntu 20.04, macOS Catalina]
- **Python Version**: [e.g., 3.10.9]
- **AgentNeo Version**: [e.g., 1.2.2]
- **Relevant Packages**: [e.g., OpenAI SDK 0.9.0, LiteLLM 1.2.3]

**AgentNeo Configuration**
Provide any custom configuration settings or code modifications:
```python
# Your custom configuration or code here
```

**Additional Context**
Add any other information about the problem here, such as:
- Network configuration
- Firewall settings
- Previous attempts to fix the issue

**Comment by Hkishore1** [comment]
Is this issue fixed? I'm also getting the same error.

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[1], line 101
     93     user_proxy.initiate_chat(
     94     manager,
     95     message="""
     96 find papers on LLM applications from arxiv in the last week, create a markdown table of different domains.
     97 """,
     98 )
    100 # Run the group chat
--> 101 run_group_chat()
    103 # Stop the tracer
    104 tracer.stop()

File c:\AgentEvalution\venv_11\Lib\site-packages\agentneo\tracing\agent_tracer.py:76, in AgentTracerMixin.trace_agent.<locals>.decorator.<locals>.sync_wrapper(*args, **kwargs)
     74 @functools.wraps(func_or_class)
     75 def sync_wrapper(*args, **kwargs):
---> 76     return self._trace_agent_call_sync(
     77         func_or_class, name, *args, **kwargs
     78     )

File c:\AgentEvalution\venv_11\Lib\site-packages\agentneo\tracing\agent_tracer.py:157, in AgentTracerMixin._trace_agent_call_sync(self, func, name, *args, **kwargs)
    155 try:
    156     with user_interaction_tracer.capture():
--> 157         result = func(*args, **kwargs)
...
    159     memory_used=memory_used,
    160 )
    162 with self.Session() as session:

KeyError: 'input_cost_per_token'
```

python : 3.11.5
agentneo : 1.2.2
openai : 1.51.2

**Comment by kiran-raga** [comment]
@Hkishore1 No the issue isn't resolved yet

**Comment by vijayc9** [comment]
@frazakram it is resolved, you can test it and update here and close the issue

test in v1.2 branch

**Comment by frazakram** [comment]
> [@frazakram](https://github.com/frazakram) it is resolved, you can test it and update here and close the issue
> 
> test in v1.2 branch

yeah thanks @vijayc9
