### ISSUE TITLE
[BUG]: Getting ModuleNotFoundError for litellm

### ISSUE THREAD

**Issue by 2011-Tushar** [raga-ai-hub/ragaai-catalyst#55]
# Bug Report

**Describe the Bug**
I have installed the latest version of agentneo. While importing the module, an error is being raised as it could not find 'litellm' in the environment.

**To Reproduce**
Steps or code snippets to reproduce the behavior, like:
```
1. Install AgentNeo using `pip install agentneo`
2. Run the following code:
   from agentneo import AgentNeo, Tracer
```

**Expected Behavior**
The module should import without any error

**Actual Behavior**
Received 'ModuleNotFoundError' for litellm

**Logs and Screenshots**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/tempenv/lib/python3.11/site-packages/agentneo/__init__.py", line 7, in <module>
    from .execution import Execution
  File "/opt/miniconda3/envs/tempenv/lib/python3.11/site-packages/agentneo/execution/__init__.py", line 1, in <module>
    from .execution import Execution
  File "/opt/miniconda3/envs/tempenv/lib/python3.11/site-packages/agentneo/execution/execution.py", line 15, in <module>
    from .metrics import (
  File "/opt/miniconda3/envs/tempenv/lib/python3.11/site-packages/agentneo/execution/metrics/__init__.py", line 1, in <module>
    from .goal_fulfillment_rate import execute_goal_fulfillment_metric
  File "/opt/miniconda3/envs/tempenv/lib/python3.11/site-packages/agentneo/execution/metrics/goal_fulfillment_rate.py", line 3, in <module>
    import litellm
ModuleNotFoundError: No module named 'litellm'
```

**Environment Details**
- **Operating System**: macOS Sonoma
- **Python Version**: 3.11.9
- **AgentNeo Version**: 1.1.1

**Comment by kiranscaria** [comment]
Resolved in version `1.1.2`
